feat(bitxhub, pier):add clean command
meshplus/goduck pull request #60
Opened 2020-08-12 12:44 UTC by dawn-to-dusk

1. Add clean bitxhub command;
2. Add clean pier command;
3. Adjust some print for stop commands of bitxhub and pier;
4. Add a default note in cmd/goduck/config.go.

2020-08-12 15:55 UTC, Alexader requested changes

2020-08-12 15:55 UTC, Alexader commented on scripts/run_pier.sh
>    pier_up
`goduck pier start` command should not remove old container or remove store now, for the reason of new command `goduck pier clean`

2020-08-19 02:26 UTC, Alexader approved these changes

2020-08-19 02:27 UTC, jzhe886 approved these changes

2020-08-19 02:28 UTC, merged