fix(pier):fix bugs in pier local deployment
meshplus/goduck pull request #73
Opened 2020-09-15 06:50 UTC by dawn-to-dusk

1. Make the version of pier-appchain consistent  with the version of pier;
2. Fix bug with different versions of binary zip or Docker image names;
3. Improve the function of pier deployment according to version.

2020-09-15 07:03 UTC, Alexader requested changes

2020-09-15 07:03 UTC, Alexader commented on scripts/run_pier.sh
> +    if [ "${VERSION}" == "v1.0.0-rc1" ]; then
should be v1.0.0 or v1.0.0-rc1?

2020-09-15 12:04 UTC, Alexader approved these changes

2020-09-17 02:39 UTC, sandyzhou approved these changes

2020-09-17 02:39 UTC, merged

2020-09-17 02:40 UTC, jzhe886 commented on cmd/goduck/pier.go
> +		if !fileutil.Exist(filepath.Join(repoRoot, fmt.Sprintf("bin/pier_%s", version))) {
is pier binary name like pier_v1.0.0-rc1?