fix(cmd/goduck/deploy):fix the bugs in bitxhub deployment
meshplus/goduck pull request #79
Opened 2020-09-22 12:01 UTC by dawn-to-dusk

1. Fix the bug about incomplete node configuration after scp command;
2. Fix the bug about "libwasmer.so: cannot open shared object file";
3. Fix the bug about unavailable bitxHub command;
4. Fix the bug about "Connect failed" due to inconsistent node startup.

2020-09-23 03:04 UTC, Alexader requested changes

2020-09-23 03:04 UTC, Alexader commented on cmd/goduck/deploy.go
> +		err = sh.Command("ssh", who, fmt.Sprintf("mkdir -p ~/build/node%d", idx+1)).
mkdir in hidden directory $HOME/.bitxhub is better?

2020-09-24 02:21 UTC, Alexader approved these changes

2020-09-24 02:33 UTC, jzhe886 approved these changes

2020-09-24 02:33 UTC, merged